version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${DB_PASSWORD}
    command: ["redis-server", "--requirepass", "${DB_PASSWORD}"]
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}    
      MYSQL_USER: ${DB_USER}               
      MYSQL_PASSWORD: ${DB_PASSWORD}    
    ports:
      - "3306:3306"                       
    volumes:
      - mysql_data:/var/lib/mysql    
      - ./sql-scripts:/docker-entrypoint-initdb.d      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql                  
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}   
    ports:
      - "8080:80"                         
    depends_on:
      - mysql                            

volumes:
  mysql_data:
  redis_data:
